#!/bin/bash
#SBATCH --job-name=CARMA_cauchy_small
#SBATCH --output=CARMA_cauchy_small.out
#SBATCH --error=CARMA_cauchy_small.err
#SBATCH --time=23:00:00
#SBATCH --partition=broadwl
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --mem-per-cpu=5000
#SBATCH --array=1-6

module load R/4.1.0
Rscript /home/wdenault/susie_small_sample/scripts/sim_script/CARMA_cauchy_sim/cama_small_n$SLURM_ARRAY_TASK_ID.R
