#!/bin/bash
#SBATCH --job-name=run_time
#SBATCH --output=run_time.out
#SBATCH --error=run_time.err
#SBATCH --time=23:00:00
#SBATCH --partition=mstephens
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --mem-per-cpu=5000

module load R/4.1.0
Rscript /home/wdenault/susie_small_sample/scripts/sim_script/computational_time_comp/test_run_time.R
