#!/bin/bash
#SBATCH --job-name=cor_small_susie
#SBATCH --output=cor_small_susie.out
#SBATCH --error=cor_small_susie.err
#SBATCH --time=23:00:00
#SBATCH --partition=mstephens
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --mem-per-cpu=5000
#SBATCH --array=1-4

module load R/4.1.0
Rscript /home/wdenault/susie_small_sample/scripts/sim_script/cor_susie_small_n$SLURM_ARRAY_TASK_ID.R
